In [1]:
#%%

import numpy as np
np.__version__

'1.23.3'

In [3]:
#%% 2. Numpy Array:

a = np.array([1,2,3,4,5])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)
x = np.arange(5)
print(x)

[1 2 3 4 5]
(5,)
int32
1
5
4
[0 1 2 3 4]


In [3]:
#%% Essential methods:

a = np.array([1,2,3])

print(a[0])
a[0] = 5
print(a)

b = a *np.array([2, 0, 2])
print(b)
print(b.sum())

1
[5 2 3]
[10  0  6]
16


In [4]:
# 3. Numpy Array vs List:

l = [1, 2, 3]
a = np.array([1,2,3])
print(l)
print(a)

l2 = 2 * l
print(l2)

a2 = 2 * a
print(a2)

[1, 2, 3]
[1 2 3]
[1, 2, 3, 1, 2, 3]
[2 4 6]


In [5]:
# 4. Dot product

a = np.array([1,2])
b = np.array([3,4])

dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
print(dot)

dot = np.dot(a,b)
print(dot)

dot = a.dot(b)
print(dot)

dot = a @ b
print(dot)

11
11
11
11


In [6]:
# 5. Speed Test Array vs List

from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)
A = list(a)
B = list(b)
T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i] * B[i]
    return dot

def dot2():
    return np.dot(a, b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end - start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end - start

print('The with lists:', t1)
print('The with array:', t2)
print('Ratio', t1/t2)

The with lists: 0.4767860999563709
The with array: 0.04233419999945909
Ratio 11.262433209142085


In [7]:
# 6. Multidimensional (nd) Arrays

a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)

print(a[0])
print(a[0][0])

print(a[0,0])

print(a[:,0])
print(a[0,:])

[[1 2]
 [3 4]]
(2, 2)
[1 2]
1
1
[1 3]
[1 2]


In [8]:
print(a.T)

[[1 3]
 [2 4]]


In [9]:
# matrix multiplication

b = np.array([[3,4], [5,6]])
c = a.dot(b)
d = a * b

print(d)

[[ 3  8]
 [15 24]]


In [10]:
c = np.linalg.det(a)
print(c)

-2.0000000000000004


In [11]:
c = np.linalg.inv(a)
print(c)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
print(a)
c = np.diag(a)
print(c)

[[1 2]
 [3 4]]
[1 4]


In [14]:
c = np.diag([1,4])
print(c)

[[1 0]
 [0 4]]


In [19]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

b = a[0,1]
print(b)

row0 = a[0,:]
print(row0)

col0 = a[:, 0]
print(col0)

slice_a = a[0:2,1:3]
print(slice_a)

last = a[-1,-1]
print(last)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[1 2 3 4]
[1 5 9]
[[2 3]
 [6 7]]
12


In [20]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

bool_idx = a > 2
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [21]:
print(a[bool_idx])

[3 4 5 6]


In [22]:
print(a[a > 2])

[3 4 5 6]


In [24]:
b = np.where(a > 2, a, -1)
print(b)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [25]:
a = np.array([10,19,30,41,50,61])
b = a[[1,3,5]]
print(b)

[19 41 61]


In [26]:
even = np.argwhere(a%2 == 0).flatten()
print(even)
a_even = a[even]
print(a_even)

[0 2 4]
[10 30 50]


In [30]:
a = np.arange(1,7)
print(a)

b = a.reshape((2,3))
print(b)

c = a.reshape((3,2))
print(c)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [31]:
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [32]:
d = a[np.newaxis, :]
print(d)
print(d.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [33]:
e = a[:, np.newaxis]
print(e)
print(e.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [34]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [35]:
c = np.concatenate((a,b), axis=None)
print(c)

[1 2 3 4 5 6]


In [36]:
d = np.concatenate((a,b), axis=0)
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
e = np.concatenate((a,b.T), axis=1)
print(e)

[[1 2 5]
 [3 4 6]]


In [41]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.hstack((a,b))
print(c)

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]


In [42]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.vstack((a,b))
print(c)

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,0,1])

c = a + b
print(c)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [44]:
a = np.array([[7,8,9,10,11,12,13], [14,15,16,17,18,19,20]])
print(a.sum())
print(a.sum(axis=None))
print(a.sum(axis=0))
print(a.sum(axis=1))

189
189
[21 23 25 27 29 31 33]
[ 70 119]


In [45]:
a = np.array([[7,8,9,10,11,12,13], [14,15,16,17,18,19,20]])
print(a.mean())
print(a.mean(axis=None))
print(a.mean(axis=0))
print(a.mean(axis=1))

13.5
13.5
[10.5 11.5 12.5 13.5 14.5 15.5 16.5]
[10. 17.]


In [47]:
x = np.array([1,2])
print(a.dtype)

y = np.array([1.0,2.0])
print(y.dtype)

x = np.array([1,2], dtype=np.int32)
print(a.dtype)

y = np.array([1.0,2.0], dtype=np.float32)
print(y.dtype)

int32
float64
int32
float32


In [48]:
a = np.array([1,2,3])
b = a
b[0] = 42

print(a)
print(b)

[42  2  3]
[42  2  3]


In [49]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [51]:
a = np.full((3,3), 5.0)
print(a)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [52]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [58]:
a = np.random.random((3,2))
print(a)

b = np.random.randn(3,2)
print(b)

[[0.93607236 0.67392295]
 [0.76266355 0.30886056]
 [0.87521315 0.70323485]]
[[-0.60597797  0.14264009]
 [-0.54590751  0.14829237]
 [ 0.41055136 -1.3913222 ]]


In [59]:
c = np.random.randn(1000)
print(c.mean(), c.var(), c.std())

0.021779259257700315 1.0339801314949242 1.0168481359057133


In [60]:
d = np.random.randn(10, 3)
print(d.mean())

0.27819185715335437


In [61]:
e = np.random.randint(10, size=(3,3))
print(e)

[[3 2 9]
 [6 4 7]
 [1 9 9]]


In [63]:
f = np.random.choice(7, size=10)
print(f)

[5 1 1 3 0 6 6 0 2 6]


In [64]:
g = np.random.choice([10, 22,39], size=10)
print(g)

[22 10 39 22 39 10 10 39 22 39]
